name: movie_hub
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

    # For ios icons
  cupertino_icons: ^1.0.2

  # For the responsiveness of the sizes given
  flutter_screenutil: ^5.7.0

  # To build svg data
  flutter_svg: ^2.0.5

  # To cache data of images to boost app performance
  cached_network_image: ^3.2.3

  # For State Management
  provider: ^6.0.5

  # For Dependency Injection
  get_it: ^7.6.2

  #To enable comparison of objects without having to override ==
  equatable: ^2.0.5

  # For Network Calls 
  http: ^1.1.0

  # For beautiful loading effects
  shimmer: ^3.0.0

  # For the slider
  carousel_slider: ^4.2.1

  # For Date Formatting
  intl: ^0.18.1

  # For loading urls
  url_launcher: ^6.2.1

  # For loading movie page
  webview_flutter: ^4.4.2

  #For nice animated assets
  lottie: ^2.7.0

  # Firebase
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.3
  firebase_storage: ^11.5.5
  firebase_crashlytics: ^3.4.8

  # Functional programming
  fpdart: ^1.1.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"  

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/lottie/

  fonts:
    - family: Sacramento
      fonts:
        - asset: assets/fonts/Sacramento-Regular.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf        
        - asset: assets/fonts/Montserrat-Bold.ttf        
        - asset: assets/fonts/Montserrat-Light.ttf        
        - asset: assets/fonts/Montserrat-Medium.ttf        
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        
    - family: Playfair    
      fonts:          
        - asset: assets/fonts/PlayfairDisplaySC-BoldItalic.ttf
          style: italic
          weight: 700        
              

 

